# Generated by Django 5.2.5 on 2025-08-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_unique_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufactured_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.shop')),
            ],
        ),
    ]
