# Generated by Django 5.2.5 on 2025-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('ER', 'Erode'), ('CBE', 'Coimbatore'), ('TPR', 'Tiruppur'), ('SLM', 'Salem'), ('NKL', 'Namakkal'), ('KRR', 'Karur')], max_length=3)),
                ('unique_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
